### ISSUE TITLE
crashes on npm start

### ISSUE THREAD

**Issue by swyxio** [fraziern/voting#2]
```
> voting@1.0.0 start /Users/swyx/Desktop/webdev/wesbos/voting
> node server.js

/Users/swyx/Desktop/webdev/wesbos/voting/node_modules/passport-oauth2/lib/strategy.js:82
  if (!options.clientID) { throw new TypeError('OAuth2Strategy requires a clientID option'); }
                           ^

TypeError: OAuth2Strategy requires a clientID option
    at Strategy.OAuth2Strategy (/Users/swyx/Desktop/webdev/wesbos/voting/node_modules/passport-oauth2/lib/strategy.js:82:34)
    at new Strategy (/Users/swyx/Desktop/webdev/wesbos/voting/node_modules/passport-github/lib/strategy.js:62:18)
    at module.exports (/Users/swyx/Desktop/webdev/wesbos/voting/js/config/passport.js:16:16)
    at Object.<anonymous> (/Users/swyx/Desktop/webdev/wesbos/voting/server.js:12:35)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! voting@1.0.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the voting@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/swyx/.npm/_logs/2017-07-07T07_23_32_997Z-debug.log

```

what are the default options needed?

**Comment by fraziern** [comment]
Hi @sw-yx - the error is probably because you don't have a .env file, which is not part of the repo but is required. ( I need to update the documentation on that - honestly I didn't think anyone would ever actually look at this :smile: )

Check out the auth config file at https://github.com/fraziern/voting/blob/master/js/config/auth.js - and the dotenv documentation at https://www.npmjs.com/package/dotenv

Let me know if you need more help.

**Comment by swyxio** [comment]
looks simple enough. ha i was just being lazy tbh i could probably figure it out if i tried hard enough but i wanted to just quickly set it up and look at the demo for myself.
